// Code generated by protoc-gen-go. DO NOT EDIT.
// source: User.proto

package User

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_NOTDEFINED Gender = 0
	Gender_MALE       Gender = 1
	Gender_FEMALE     Gender = 2
)

var Gender_name = map[int32]string{
	0: "NOTDEFINED",
	1: "MALE",
	2: "FEMALE",
}

var Gender_value = map[string]int32{
	"NOTDEFINED": 0,
	"MALE":       1,
	"FEMALE":     2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{0}
}

type LinkUserRequest struct {
	TvEmac               string   `protobuf:"bytes,1,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkUserRequest) Reset()         { *m = LinkUserRequest{} }
func (m *LinkUserRequest) String() string { return proto.CompactTextString(m) }
func (*LinkUserRequest) ProtoMessage()    {}
func (*LinkUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{0}
}

func (m *LinkUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkUserRequest.Unmarshal(m, b)
}
func (m *LinkUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkUserRequest.Marshal(b, m, deterministic)
}
func (m *LinkUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkUserRequest.Merge(m, src)
}
func (m *LinkUserRequest) XXX_Size() int {
	return xxx_messageInfo_LinkUserRequest.Size(m)
}
func (m *LinkUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkUserRequest proto.InternalMessageInfo

func (m *LinkUserRequest) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

type LinkUserResponse struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkUserResponse) Reset()         { *m = LinkUserResponse{} }
func (m *LinkUserResponse) String() string { return proto.CompactTextString(m) }
func (*LinkUserResponse) ProtoMessage()    {}
func (*LinkUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{1}
}

func (m *LinkUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkUserResponse.Unmarshal(m, b)
}
func (m *LinkUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkUserResponse.Marshal(b, m, deterministic)
}
func (m *LinkUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkUserResponse.Merge(m, src)
}
func (m *LinkUserResponse) XXX_Size() int {
	return xxx_messageInfo_LinkUserResponse.Size(m)
}
func (m *LinkUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkUserResponse proto.InternalMessageInfo

func (m *LinkUserResponse) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

type RemoveTvDeviceRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	TvEmac               string   `protobuf:"bytes,2,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTvDeviceRequest) Reset()         { *m = RemoveTvDeviceRequest{} }
func (m *RemoveTvDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTvDeviceRequest) ProtoMessage()    {}
func (*RemoveTvDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{2}
}

func (m *RemoveTvDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTvDeviceRequest.Unmarshal(m, b)
}
func (m *RemoveTvDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTvDeviceRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTvDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTvDeviceRequest.Merge(m, src)
}
func (m *RemoveTvDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTvDeviceRequest.Size(m)
}
func (m *RemoveTvDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTvDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTvDeviceRequest proto.InternalMessageInfo

func (m *RemoveTvDeviceRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *RemoveTvDeviceRequest) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

type RemoveTvDeviceResponse struct {
	IsTvDeviceRemoved    bool     `protobuf:"varint,1,opt,name=isTvDeviceRemoved,proto3" json:"isTvDeviceRemoved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTvDeviceResponse) Reset()         { *m = RemoveTvDeviceResponse{} }
func (m *RemoveTvDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveTvDeviceResponse) ProtoMessage()    {}
func (*RemoveTvDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{3}
}

func (m *RemoveTvDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTvDeviceResponse.Unmarshal(m, b)
}
func (m *RemoveTvDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTvDeviceResponse.Marshal(b, m, deterministic)
}
func (m *RemoveTvDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTvDeviceResponse.Merge(m, src)
}
func (m *RemoveTvDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveTvDeviceResponse.Size(m)
}
func (m *RemoveTvDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTvDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTvDeviceResponse proto.InternalMessageInfo

func (m *RemoveTvDeviceResponse) GetIsTvDeviceRemoved() bool {
	if m != nil {
		return m.IsTvDeviceRemoved
	}
	return false
}

type GetRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

type DeleteRequest struct {
	GoogleId             string   `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

type DeleteReponse struct {
	IsDeleted            bool     `protobuf:"varint,1,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReponse) Reset()         { *m = DeleteReponse{} }
func (m *DeleteReponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReponse) ProtoMessage()    {}
func (*DeleteReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{6}
}

func (m *DeleteReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReponse.Unmarshal(m, b)
}
func (m *DeleteReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReponse.Marshal(b, m, deterministic)
}
func (m *DeleteReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReponse.Merge(m, src)
}
func (m *DeleteReponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReponse.Size(m)
}
func (m *DeleteReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReponse proto.InternalMessageInfo

func (m *DeleteReponse) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type LinkedDeviceResponse struct {
	IsLinkedDeviceFetched bool            `protobuf:"varint,1,opt,name=isLinkedDeviceFetched,proto3" json:"isLinkedDeviceFetched,omitempty"`
	LinkedDevices         []*LinkedDevice `protobuf:"bytes,2,rep,name=linkedDevices,proto3" json:"linkedDevices,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}        `json:"-"`
	XXX_unrecognized      []byte          `json:"-"`
	XXX_sizecache         int32           `json:"-"`
}

func (m *LinkedDeviceResponse) Reset()         { *m = LinkedDeviceResponse{} }
func (m *LinkedDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*LinkedDeviceResponse) ProtoMessage()    {}
func (*LinkedDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{7}
}

func (m *LinkedDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkedDeviceResponse.Unmarshal(m, b)
}
func (m *LinkedDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkedDeviceResponse.Marshal(b, m, deterministic)
}
func (m *LinkedDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedDeviceResponse.Merge(m, src)
}
func (m *LinkedDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_LinkedDeviceResponse.Size(m)
}
func (m *LinkedDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedDeviceResponse proto.InternalMessageInfo

func (m *LinkedDeviceResponse) GetIsLinkedDeviceFetched() bool {
	if m != nil {
		return m.IsLinkedDeviceFetched
	}
	return false
}

func (m *LinkedDeviceResponse) GetLinkedDevices() []*LinkedDevice {
	if m != nil {
		return m.LinkedDevices
	}
	return nil
}

type TvDevice struct {
	GoogleId             string        `protobuf:"bytes,1,opt,name=googleId,proto3" json:"googleId,omitempty"`
	LinkedDevice         *LinkedDevice `protobuf:"bytes,2,opt,name=linkedDevice,proto3" json:"linkedDevice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TvDevice) Reset()         { *m = TvDevice{} }
func (m *TvDevice) String() string { return proto.CompactTextString(m) }
func (*TvDevice) ProtoMessage()    {}
func (*TvDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{8}
}

func (m *TvDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TvDevice.Unmarshal(m, b)
}
func (m *TvDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TvDevice.Marshal(b, m, deterministic)
}
func (m *TvDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TvDevice.Merge(m, src)
}
func (m *TvDevice) XXX_Size() int {
	return xxx_messageInfo_TvDevice.Size(m)
}
func (m *TvDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_TvDevice.DiscardUnknown(m)
}

var xxx_messageInfo_TvDevice proto.InternalMessageInfo

func (m *TvDevice) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *TvDevice) GetLinkedDevice() *LinkedDevice {
	if m != nil {
		return m.LinkedDevice
	}
	return nil
}

type UpdateResponse struct {
	IsUpdated            bool     `protobuf:"varint,1,opt,name=isUpdated,proto3" json:"isUpdated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{9}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetIsUpdated() bool {
	if m != nil {
		return m.IsUpdated
	}
	return false
}

type CreateReponse struct {
	IsCreated            bool     `protobuf:"varint,1,opt,name=isCreated,proto3" json:"isCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReponse) Reset()         { *m = CreateReponse{} }
func (m *CreateReponse) String() string { return proto.CompactTextString(m) }
func (*CreateReponse) ProtoMessage()    {}
func (*CreateReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{10}
}

func (m *CreateReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReponse.Unmarshal(m, b)
}
func (m *CreateReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReponse.Marshal(b, m, deterministic)
}
func (m *CreateReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReponse.Merge(m, src)
}
func (m *CreateReponse) XXX_Size() int {
	return xxx_messageInfo_CreateReponse.Size(m)
}
func (m *CreateReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReponse proto.InternalMessageInfo

func (m *CreateReponse) GetIsCreated() bool {
	if m != nil {
		return m.IsCreated
	}
	return false
}

// Date dd/MM/YYYY
type User struct {
	// important_string must be a lowercase alpha-numeric of 5 to 30 characters (RE2 syntax).
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	GoogleId             string               `protobuf:"bytes,4,opt,name=googleId,proto3" json:"googleId,omitempty"`
	DateOfBirth          *date.Date           `protobuf:"bytes,5,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	Gender               Gender               `protobuf:"varint,12,opt,name=gender,proto3,enum=User.Gender" json:"gender,omitempty"`
	ImageUrl             string               `protobuf:"bytes,13,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Genre                []string             `protobuf:"bytes,6,rep,name=genre,proto3" json:"genre,omitempty"`
	Language             []string             `protobuf:"bytes,7,rep,name=language,proto3" json:"language,omitempty"`
	ContentType          []string             `protobuf:"bytes,8,rep,name=contentType,proto3" json:"contentType,omitempty"`
	LinkedDevices        []*LinkedDevice      `protobuf:"bytes,9,rep,name=linkedDevices,proto3" json:"linkedDevices,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{11}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetGoogleId() string {
	if m != nil {
		return m.GoogleId
	}
	return ""
}

func (m *User) GetDateOfBirth() *date.Date {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *User) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_NOTDEFINED
}

func (m *User) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *User) GetGenre() []string {
	if m != nil {
		return m.Genre
	}
	return nil
}

func (m *User) GetLanguage() []string {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *User) GetContentType() []string {
	if m != nil {
		return m.ContentType
	}
	return nil
}

func (m *User) GetLinkedDevices() []*LinkedDevice {
	if m != nil {
		return m.LinkedDevices
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type LinkedDevice struct {
	TvEmac               string   `protobuf:"bytes,1,opt,name=tvEmac,proto3" json:"tvEmac,omitempty"`
	TvPanel              string   `protobuf:"bytes,2,opt,name=tvPanel,proto3" json:"tvPanel,omitempty"`
	TvBoard              string   `protobuf:"bytes,3,opt,name=tvBoard,proto3" json:"tvBoard,omitempty"`
	TvName               string   `protobuf:"bytes,4,opt,name=tvName,proto3" json:"tvName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkedDevice) Reset()         { *m = LinkedDevice{} }
func (m *LinkedDevice) String() string { return proto.CompactTextString(m) }
func (*LinkedDevice) ProtoMessage()    {}
func (*LinkedDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{12}
}

func (m *LinkedDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkedDevice.Unmarshal(m, b)
}
func (m *LinkedDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkedDevice.Marshal(b, m, deterministic)
}
func (m *LinkedDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkedDevice.Merge(m, src)
}
func (m *LinkedDevice) XXX_Size() int {
	return xxx_messageInfo_LinkedDevice.Size(m)
}
func (m *LinkedDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkedDevice.DiscardUnknown(m)
}

var xxx_messageInfo_LinkedDevice proto.InternalMessageInfo

func (m *LinkedDevice) GetTvEmac() string {
	if m != nil {
		return m.TvEmac
	}
	return ""
}

func (m *LinkedDevice) GetTvPanel() string {
	if m != nil {
		return m.TvPanel
	}
	return ""
}

func (m *LinkedDevice) GetTvBoard() string {
	if m != nil {
		return m.TvBoard
	}
	return ""
}

func (m *LinkedDevice) GetTvName() string {
	if m != nil {
		return m.TvName
	}
	return ""
}

func init() {
	proto.RegisterEnum("User.Gender", Gender_name, Gender_value)
	proto.RegisterType((*LinkUserRequest)(nil), "User.LinkUserRequest")
	proto.RegisterType((*LinkUserResponse)(nil), "User.LinkUserResponse")
	proto.RegisterType((*RemoveTvDeviceRequest)(nil), "User.RemoveTvDeviceRequest")
	proto.RegisterType((*RemoveTvDeviceResponse)(nil), "User.RemoveTvDeviceResponse")
	proto.RegisterType((*GetRequest)(nil), "User.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "User.DeleteRequest")
	proto.RegisterType((*DeleteReponse)(nil), "User.DeleteReponse")
	proto.RegisterType((*LinkedDeviceResponse)(nil), "User.LinkedDeviceResponse")
	proto.RegisterType((*TvDevice)(nil), "User.TvDevice")
	proto.RegisterType((*UpdateResponse)(nil), "User.UpdateResponse")
	proto.RegisterType((*CreateReponse)(nil), "User.CreateReponse")
	proto.RegisterType((*User)(nil), "User.User")
	proto.RegisterType((*LinkedDevice)(nil), "User.LinkedDevice")
}

func init() {
	proto.RegisterFile("User.proto", fileDescriptor_979821478719c248)
}

var fileDescriptor_979821478719c248 = []byte{
	// 1374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x7f, 0x6f, 0xd3, 0xc6,
	0x1b, 0xff, 0xba, 0x3f, 0xd3, 0x27, 0xa5, 0xdf, 0x72, 0x1b, 0x25, 0xa4, 0x55, 0x73, 0x33, 0x85,
	0x15, 0x8f, 0xc4, 0x6d, 0xd9, 0x18, 0x54, 0x62, 0x23, 0x69, 0xd3, 0xaa, 0x52, 0x69, 0x59, 0x9a,
	0x4e, 0x0c, 0x04, 0xda, 0x25, 0x3e, 0x1c, 0x0b, 0xc7, 0xce, 0x7c, 0x97, 0xa0, 0x0e, 0x21, 0x21,
	0x34, 0x4d, 0xd3, 0xfe, 0x1c, 0xef, 0x62, 0x6f, 0x67, 0x2f, 0x20, 0x52, 0xb4, 0x17, 0x32, 0xdd,
	0x9d, 0x9d, 0x38, 0x4e, 0xd8, 0xd8, 0xe0, 0xaf, 0xd8, 0xcf, 0xf3, 0x79, 0x3e, 0xcf, 0xcf, 0x7b,
	0x7c, 0x01, 0x38, 0x65, 0x34, 0x28, 0xb4, 0x02, 0x9f, 0xfb, 0x68, 0x4a, 0x3c, 0x67, 0x97, 0x6d,
	0xdf, 0xb7, 0x5d, 0x6a, 0x4a, 0x59, 0xad, 0xfd, 0xd4, 0xa4, 0xcd, 0x16, 0x3f, 0x53, 0x90, 0x6c,
	0x2e, 0xa9, 0xe4, 0x4e, 0x93, 0x32, 0x4e, 0x9a, 0xad, 0x10, 0xb0, 0x14, 0x02, 0xf8, 0x59, 0x8b,
	0x9a, 0x16, 0xe1, 0x34, 0x94, 0xaf, 0x84, 0x72, 0xd2, 0x72, 0x4c, 0xe2, 0x79, 0x3e, 0x27, 0xdc,
	0xf1, 0x3d, 0x16, 0x6a, 0xaf, 0xcb, 0x9f, 0x7a, 0xde, 0xa6, 0x5e, 0x9e, 0x3d, 0x27, 0xb6, 0x4d,
	0x03, 0xd3, 0x6f, 0x49, 0xc4, 0x18, 0xf4, 0x4d, 0xdb, 0xe1, 0x8d, 0x76, 0xad, 0x50, 0xf7, 0x9b,
	0x66, 0xf3, 0xb9, 0xc3, 0x9f, 0xf9, 0xcf, 0x4d, 0xdb, 0xcf, 0x4b, 0x65, 0xbe, 0x43, 0x5c, 0xc7,
	0x22, 0xdc, 0x0f, 0x98, 0xd9, 0x7f, 0x54, 0x76, 0xfa, 0x3d, 0xf8, 0xff, 0xa1, 0xe3, 0x3d, 0x13,
	0x59, 0x56, 0xe8, 0x0f, 0x6d, 0xca, 0x38, 0xda, 0x86, 0x19, 0xde, 0x29, 0x37, 0x49, 0x3d, 0xa3,
	0x61, 0x6d, 0x7d, 0xae, 0xa4, 0xf7, 0xba, 0xb9, 0x55, 0xac, 0x19, 0x99, 0x6a, 0x07, 0x0b, 0x31,
	0xae, 0x4b, 0xf7, 0xb8, 0x46, 0xb1, 0x2a, 0xc3, 0x03, 0xad, 0x12, 0x5a, 0xe8, 0x5b, 0xb0, 0x38,
	0xa0, 0x63, 0x2d, 0xdf, 0x63, 0x14, 0xad, 0xc2, 0x54, 0x9b, 0xd1, 0x20, 0xa3, 0xe1, 0xc9, 0xf5,
	0xf4, 0x16, 0x14, 0x64, 0x75, 0x25, 0x42, 0xca, 0xf5, 0x37, 0x1a, 0x5c, 0xa8, 0xd0, 0xa6, 0xdf,
	0xa1, 0xd5, 0xce, 0x2e, 0xed, 0x38, 0x75, 0x1a, 0x45, 0xf2, 0x15, 0xa4, 0x54, 0x89, 0x0e, 0xac,
	0x64, 0x2c, 0xc2, 0x1e, 0x1f, 0x58, 0xe3, 0x62, 0xe9, 0xdb, 0xc4, 0x32, 0x99, 0xf8, 0xd7, 0x99,
	0xec, 0xc1, 0x52, 0x32, 0xa8, 0x30, 0x9f, 0xeb, 0x70, 0xde, 0x61, 0x03, 0xa9, 0xc0, 0xa8, 0xf0,
	0x52, 0x95, 0x51, 0x85, 0x7e, 0x08, 0xb0, 0x4f, 0xf9, 0x07, 0xca, 0x48, 0x3f, 0x86, 0x73, 0xbb,
	0xd4, 0xa5, 0xfc, 0x43, 0x95, 0x48, 0xcf, 0x0f, 0x08, 0x55, 0x76, 0x2b, 0x30, 0xe7, 0x30, 0x25,
	0x8a, 0xb2, 0x1a, 0x08, 0xf4, 0x9f, 0x35, 0xf8, 0x58, 0x34, 0x98, 0x5a, 0x89, 0xa2, 0x7c, 0x0e,
	0x17, 0x1c, 0x16, 0xd7, 0xec, 0x51, 0x5e, 0x6f, 0xf4, 0x29, 0xc6, 0x2b, 0xd1, 0x2d, 0x38, 0xe7,
	0xc6, 0xc4, 0x2c, 0x33, 0x21, 0x67, 0x04, 0xa9, 0x19, 0x19, 0x72, 0x34, 0x0c, 0xd4, 0x5f, 0x6b,
	0x90, 0x8a, 0x4a, 0xfd, 0xde, 0x73, 0x72, 0x13, 0xe6, 0xe3, 0xec, 0x72, 0x5a, 0xc6, 0x47, 0x31,
	0x84, 0xd3, 0x0b, 0xb0, 0x70, 0xda, 0x12, 0x07, 0xba, 0x5f, 0x06, 0x59, 0x3d, 0x25, 0x8b, 0x55,
	0x2f, 0x14, 0x88, 0x62, 0xef, 0x04, 0x94, 0x24, 0x8a, 0xad, 0x44, 0x31, 0x78, 0x28, 0xd0, 0x7f,
	0x4f, 0x81, 0x5c, 0x3f, 0xe8, 0x1e, 0x4c, 0x79, 0xa4, 0x49, 0xc3, 0xdc, 0x6e, 0xf7, 0xba, 0xb9,
	0x2f, 0xe0, 0xfc, 0x93, 0x47, 0x24, 0xff, 0x63, 0x31, 0xff, 0x10, 0x3f, 0x7e, 0x71, 0xe3, 0xfa,
	0xd6, 0xc6, 0xcb, 0x35, 0x03, 0xcb, 0x64, 0x05, 0x32, 0x4a, 0xb7, 0xee, 0x7b, 0x9c, 0x38, 0x1e,
	0x3e, 0x6a, 0x37, 0x6b, 0x34, 0x60, 0x15, 0x49, 0x83, 0xee, 0xc2, 0x34, 0x6d, 0x12, 0xc7, 0x0d,
	0x4f, 0x85, 0xd1, 0xeb, 0xe6, 0xae, 0x62, 0xcd, 0x10, 0x47, 0xc2, 0x71, 0xb1, 0x63, 0x25, 0xad,
	0xa3, 0xa2, 0x3d, 0xd0, 0x2a, 0xca, 0x10, 0xbd, 0xd2, 0x20, 0xdd, 0x6a, 0xf8, 0x1e, 0x55, 0xc4,
	0x99, 0x49, 0x49, 0xf4, 0xa4, 0xd7, 0xcd, 0x3d, 0x84, 0xd4, 0x93, 0x47, 0x1b, 0xf9, 0xdb, 0x8f,
	0x8d, 0x35, 0xac, 0x19, 0xfb, 0xf7, 0x05, 0x08, 0x7b, 0x12, 0x85, 0x9b, 0x6d, 0x26, 0x3b, 0xe0,
	0x3f, 0xc5, 0x9b, 0x1b, 0xd8, 0x72, 0x6c, 0x87, 0x63, 0xe2, 0x59, 0x98, 0x35, 0xfc, 0xb6, 0x6b,
	0x09, 0x4d, 0xdd, 0xf7, 0x98, 0xc3, 0xb8, 0x40, 0xf8, 0x9e, 0x7b, 0x16, 0x1a, 0xb2, 0xc2, 0x03,
	0xed, 0x95, 0x06, 0x95, 0xb8, 0xcb, 0xa1, 0x9e, 0x4f, 0xfd, 0x87, 0x9e, 0x3f, 0x86, 0xb4, 0x68,
	0xca, 0xf1, 0xd3, 0x92, 0x13, 0xf0, 0x46, 0x66, 0x5a, 0xb6, 0xfc, 0x7c, 0x41, 0xe9, 0x0b, 0x62,
	0x55, 0x17, 0x76, 0x09, 0xa7, 0xa5, 0xf5, 0x5e, 0x37, 0x27, 0x52, 0x59, 0x15, 0x6f, 0x22, 0xb0,
	0x9a, 0xc0, 0x8f, 0xe3, 0x8e, 0xf3, 0xa1, 0x13, 0x98, 0xb1, 0xa9, 0x67, 0xd1, 0x20, 0x33, 0x8f,
	0xb5, 0xf5, 0x85, 0xad, 0x79, 0x35, 0x4c, 0xfb, 0x52, 0x56, 0xca, 0xf7, 0xba, 0xb9, 0x6b, 0x58,
	0x33, 0x74, 0xf5, 0x9e, 0x64, 0xc3, 0x7e, 0x80, 0x0f, 0x3c, 0xb9, 0xaa, 0x0b, 0xbf, 0x68, 0x5a,
	0x25, 0xa4, 0x42, 0x77, 0x21, 0xe5, 0x34, 0x89, 0x4d, 0x4f, 0x03, 0x37, 0x73, 0x4e, 0xe6, 0xbc,
	0xd6, 0xeb, 0xe6, 0x30, 0xd6, 0x8c, 0xec, 0x81, 0x90, 0xe3, 0xd3, 0xc0, 0x1d, 0x9b, 0x75, 0x64,
	0x85, 0xbe, 0x83, 0x69, 0x9b, 0x7a, 0x01, 0xcd, 0xcc, 0xe0, 0xc9, 0xf5, 0xb9, 0xd2, 0x4e, 0xaf,
	0x9b, 0xfb, 0x1a, 0x6b, 0xc6, 0x97, 0xf7, 0x5d, 0x4a, 0x18, 0xc5, 0x27, 0xd4, 0xa5, 0x75, 0x8e,
	0xf7, 0x05, 0x04, 0xdb, 0x72, 0x0c, 0x03, 0xcc, 0x1b, 0xc4, 0xc3, 0x37, 0x64, 0xa7, 0x46, 0xb9,
	0xbf, 0x9f, 0xac, 0x28, 0x46, 0x54, 0x83, 0x94, 0x4b, 0x3c, 0xbb, 0x4d, 0x6c, 0x9a, 0x99, 0x95,
	0xec, 0x7b, 0xbd, 0x6e, 0xae, 0x84, 0x35, 0x63, 0x7b, 0x98, 0xfd, 0x30, 0x44, 0xbd, 0xb3, 0x83,
	0x3e, 0x2f, 0x7a, 0x06, 0x69, 0x31, 0x94, 0xd4, 0xe3, 0xd5, 0xb3, 0x16, 0xcd, 0xa4, 0xa4, 0x9b,
	0x83, 0x5e, 0x37, 0x57, 0xc6, 0x9a, 0x71, 0x67, 0xd8, 0xcd, 0xce, 0x00, 0xf8, 0xce, 0x9e, 0xe2,
	0xec, 0xa3, 0xcb, 0x69, 0xee, 0x1d, 0x97, 0x13, 0xba, 0x05, 0x73, 0x75, 0x75, 0x86, 0x8b, 0x3c,
	0x03, 0x72, 0xb2, 0xb2, 0xd1, 0x64, 0x45, 0xb7, 0x84, 0x42, 0x35, 0xba, 0x25, 0x54, 0x06, 0x60,
	0x61, 0xd9, 0x56, 0xcb, 0xa2, 0xc8, 0x33, 0xe9, 0x7f, 0xb6, 0xec, 0x83, 0xf5, 0x9f, 0x26, 0x60,
	0x3e, 0x1e, 0xd3, 0xfb, 0x7c, 0xc6, 0xd1, 0x1d, 0x98, 0xe5, 0x9d, 0xfb, 0xc4, 0xa3, 0xd1, 0x8e,
	0xb8, 0xdc, 0xeb, 0xe6, 0x72, 0x58, 0x33, 0x2e, 0x55, 0x3b, 0x58, 0xca, 0xc7, 0x59, 0x47, 0x36,
	0xca, 0xbc, 0xe4, 0x93, 0xc0, 0x0a, 0x37, 0x43, 0xdc, 0x5c, 0xca, 0xdf, 0x62, 0x2e, 0x75, 0x2a,
	0xf2, 0x23, 0xb1, 0xf0, 0xa6, 0x46, 0x22, 0x3f, 0x8a, 0x6d, 0xb7, 0x44, 0xe4, 0x42, 0x65, 0x14,
	0x60, 0x46, 0x9d, 0x29, 0xb4, 0x00, 0x70, 0x74, 0x5c, 0xdd, 0x2d, 0xef, 0x1d, 0x1c, 0x95, 0x77,
	0x17, 0xff, 0x87, 0x52, 0x30, 0x75, 0xaf, 0x78, 0x58, 0x5e, 0xd4, 0x10, 0xc0, 0xcc, 0x5e, 0x59,
	0x3e, 0x4f, 0x6c, 0xfd, 0x3a, 0x0b, 0x69, 0xd1, 0xcf, 0x13, 0x1a, 0xc8, 0xaa, 0x7d, 0x03, 0xb3,
	0x45, 0xcb, 0x92, 0x5b, 0x37, 0x76, 0x53, 0xc9, 0x2e, 0x8d, 0x34, 0xa1, 0x2c, 0x3c, 0xeb, 0xfa,
	0xeb, 0x3f, 0xfe, 0x7c, 0x33, 0xb1, 0xa2, 0x5f, 0x34, 0xc5, 0x55, 0x86, 0x29, 0x12, 0xb3, 0xb3,
	0x69, 0x12, 0x45, 0xb2, 0xad, 0x19, 0xa8, 0x0a, 0x73, 0x87, 0x0e, 0xe3, 0xe2, 0x95, 0xa1, 0xb7,
	0x10, 0x65, 0x63, 0xce, 0xf4, 0x4f, 0x24, 0xe9, 0x32, 0xba, 0x94, 0x24, 0x75, 0x23, 0x9a, 0x0d,
	0x0d, 0x9d, 0xc0, 0xec, 0x3e, 0x95, 0x6f, 0x68, 0x31, 0xda, 0x2d, 0xd1, 0x35, 0x63, 0x88, 0xcd,
	0x90, 0x6c, 0x6b, 0x48, 0x4f, 0xb2, 0xd9, 0xca, 0xdc, 0x7c, 0x11, 0xed, 0xc4, 0x97, 0xe8, 0x5b,
	0x00, 0xf5, 0xad, 0x1a, 0x29, 0x40, 0x9c, 0x71, 0x43, 0x32, 0x1a, 0xd9, 0x2b, 0x49, 0xc6, 0x76,
	0xdf, 0x36, 0x46, 0x2a, 0x4a, 0x40, 0x01, 0xd4, 0x0d, 0x42, 0xf2, 0x7e, 0xa4, 0xb8, 0x86, 0x2e,
	0x32, 0xd9, 0x84, 0x50, 0x7e, 0x1f, 0xf5, 0xbc, 0xf4, 0xf4, 0xa9, 0x31, 0xe2, 0xc9, 0xea, 0xb3,
	0xc5, 0xc3, 0x27, 0x90, 0x2e, 0x5a, 0x56, 0xff, 0x5a, 0xb0, 0xa0, 0x28, 0xa3, 0xf7, 0x6c, 0x76,
	0xcc, 0xc9, 0x0d, 0x3f, 0xdc, 0xfa, 0x55, 0xe9, 0x09, 0xeb, 0xcb, 0x63, 0x1a, 0x19, 0x11, 0x88,
	0x4c, 0x3a, 0xb0, 0x30, 0x7c, 0x2d, 0x44, 0xcb, 0x8a, 0x75, 0xec, 0x0d, 0x36, 0xbb, 0x32, 0x5e,
	0x19, 0x3a, 0xbd, 0x26, 0x9d, 0x5e, 0xd6, 0x57, 0x93, 0x4e, 0x83, 0x21, 0xbc, 0xf0, 0xcb, 0x60,
	0x71, 0x9f, 0xf2, 0xc3, 0xa1, 0x35, 0x33, 0xda, 0xf7, 0xbf, 0xcb, 0x70, 0x53, 0x3a, 0xfb, 0x0c,
	0x5d, 0x1b, 0x33, 0x07, 0xc2, 0x20, 0x64, 0x8d, 0xd7, 0xd3, 0x83, 0x85, 0xbe, 0x53, 0x35, 0xbe,
	0x17, 0x06, 0x0e, 0x62, 0x7f, 0x19, 0xb2, 0x4b, 0x49, 0x31, 0x1b, 0xea, 0x1f, 0xba, 0xf2, 0x16,
	0x9f, 0x92, 0xd4, 0x7c, 0xa1, 0xb6, 0xce, 0xcb, 0x52, 0xe5, 0xb7, 0xe2, 0x31, 0x9a, 0xde, 0x9a,
	0xdc, 0x2c, 0x6c, 0x18, 0xda, 0x44, 0xb0, 0x03, 0x17, 0xe5, 0xa7, 0x3c, 0x3c, 0x9b, 0x38, 0xa0,
	0x2d, 0x9f, 0x39, 0xdc, 0x0f, 0xce, 0xd0, 0x7a, 0x83, 0xf3, 0x16, 0xdb, 0x36, 0xcd, 0xd8, 0xdf,
	0x1e, 0x1e, 0x10, 0x8f, 0x91, 0x4e, 0xe0, 0x9b, 0xb1, 0x03, 0x5d, 0x9b, 0x91, 0x07, 0xed, 0xc6,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x8d, 0xae, 0xd7, 0xd5, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error)
	ListUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UserService_ListUsersClient, error)
	GetUser(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReponse, error)
	AddTvDevice(ctx context.Context, in *TvDevice, opts ...grpc.CallOption) (*LinkedDeviceResponse, error)
	// tv emac without collons
	RemoveTvDevice(ctx context.Context, in *RemoveTvDeviceRequest, opts ...grpc.CallOption) (*RemoveTvDeviceResponse, error)
	GetLinkedDevices(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*LinkedDeviceResponse, error)
	GetLinkedUsers(ctx context.Context, in *LinkUserRequest, opts ...grpc.CallOption) (*LinkUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/User.UserService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UserService_ListUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserService_serviceDesc.Streams[0], "/User.UserService/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ListUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceListUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceListUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/User.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/User.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReponse, error) {
	out := new(DeleteReponse)
	err := c.cc.Invoke(ctx, "/User.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddTvDevice(ctx context.Context, in *TvDevice, opts ...grpc.CallOption) (*LinkedDeviceResponse, error) {
	out := new(LinkedDeviceResponse)
	err := c.cc.Invoke(ctx, "/User.UserService/AddTvDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveTvDevice(ctx context.Context, in *RemoveTvDeviceRequest, opts ...grpc.CallOption) (*RemoveTvDeviceResponse, error) {
	out := new(RemoveTvDeviceResponse)
	err := c.cc.Invoke(ctx, "/User.UserService/RemoveTvDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetLinkedDevices(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*LinkedDeviceResponse, error) {
	out := new(LinkedDeviceResponse)
	err := c.cc.Invoke(ctx, "/User.UserService/GetLinkedDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetLinkedUsers(ctx context.Context, in *LinkUserRequest, opts ...grpc.CallOption) (*LinkUserResponse, error) {
	out := new(LinkUserResponse)
	err := c.cc.Invoke(ctx, "/User.UserService/GetLinkedUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	AddUser(context.Context, *User) (*empty.Empty, error)
	ListUsers(*empty.Empty, UserService_ListUsersServer) error
	GetUser(context.Context, *GetRequest) (*User, error)
	UpdateUser(context.Context, *User) (*User, error)
	DeleteUser(context.Context, *DeleteRequest) (*DeleteReponse, error)
	AddTvDevice(context.Context, *TvDevice) (*LinkedDeviceResponse, error)
	// tv emac without collons
	RemoveTvDevice(context.Context, *RemoveTvDeviceRequest) (*RemoveTvDeviceResponse, error)
	GetLinkedDevices(context.Context, *GetRequest) (*LinkedDeviceResponse, error)
	GetLinkedUsers(context.Context, *LinkUserRequest) (*LinkUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) AddUser(ctx context.Context, req *User) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedUserServiceServer) ListUsers(req *empty.Empty, srv UserService_ListUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteRequest) (*DeleteReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) AddTvDevice(ctx context.Context, req *TvDevice) (*LinkedDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTvDevice not implemented")
}
func (*UnimplementedUserServiceServer) RemoveTvDevice(ctx context.Context, req *RemoveTvDeviceRequest) (*RemoveTvDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTvDevice not implemented")
}
func (*UnimplementedUserServiceServer) GetLinkedDevices(ctx context.Context, req *GetRequest) (*LinkedDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkedDevices not implemented")
}
func (*UnimplementedUserServiceServer) GetLinkedUsers(ctx context.Context, req *LinkUserRequest) (*LinkUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinkedUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ListUsers(m, &userServiceListUsersServer{stream})
}

type UserService_ListUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceListUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceListUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddTvDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TvDevice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddTvDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.UserService/AddTvDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddTvDevice(ctx, req.(*TvDevice))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveTvDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTvDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveTvDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.UserService/RemoveTvDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveTvDevice(ctx, req.(*RemoveTvDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetLinkedDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetLinkedDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.UserService/GetLinkedDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetLinkedDevices(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetLinkedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetLinkedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.UserService/GetLinkedUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetLinkedUsers(ctx, req.(*LinkUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "User.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "AddTvDevice",
			Handler:    _UserService_AddTvDevice_Handler,
		},
		{
			MethodName: "RemoveTvDevice",
			Handler:    _UserService_RemoveTvDevice_Handler,
		},
		{
			MethodName: "GetLinkedDevices",
			Handler:    _UserService_GetLinkedDevices_Handler,
		},
		{
			MethodName: "GetLinkedUsers",
			Handler:    _UserService_GetLinkedUsers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserService_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "User.proto",
}
